baseurl = "https://ericpettengill.github.io/ep"
title = "EP"
theme = "hugo-coder"
publishDir = "docs"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Eric Pettengill"
info = "Sr Data Scientist @ Caterpillar Inc."
description = "John Doe's personal website"
keywords = "blog,developer,personal"
avatarURL = "images/headshot.jpg"
#gravatar = "ericpettengill@gmail.com"
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
#[[params.social]]
#  name = "Github"
#  icon = "fa fa-github fa-2x"
#  weight = 1
#  url = "https://github.com/ericpettengill/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/eric-pettengill/"
[[params.social]]
  name = "instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/eric.pettengill/"
[[params.social]]
  name = "email"
  icon = "fa fa-envelope fa-2x"
  weight = 4
  url = "mailto:ericpettengill@gmail.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"